blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://discordapp.com/channels/146584994125447168/727108575507513415
    about: Questions about the bot can be asked here: (works for Speasy members only)
