blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://discordapp.com/channels/146584994125447168/766293980093743165/
    about: Link only works for Speasy members
  - name: Bot command reference and wiki
    about: (Work in progress)
    url: https://github.com/rik079/Speasier/wiki
