blank_issues_enabled: true
contact_links:
  - name: Ask a question on \#coders
    url: https://discordapp.com/channels/146584994125447168/727108575507513415
    about: Link only works for Speasy members
